In [1]:
import sys
# this is how we shall install packages in these notebooks
# !{sys.executable} -m pip install <package_name>
# !{sys.executable} -m pip install numpy
# !{sys.executable} -m pip install seaborn

import pandas as pd
import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from numpy import ndarray as array

# from sklearn.externals import joblib

In [ ]:
# -------------------------------------- REGRESSION ----------------------------------------------------------

In [11]:
# this is the hello world of machine learning. learn it by heart

In [3]:
# this is just a personal function. don't take it seriously

def get_model_details(model):
    # get the value of the coefficient(r_squared) which can tell you how well the model is fitting your data
    r_squared = model.score(x, y)
    print(f"the coefficient r_squared is {r_squared}.")

    # you can also get the y-interecpt and the slope
    y_intercept = model.intercept_
    print(f"the y-intercept is {y_intercept}")

    slope = model.coef_
    print(f"the slope is {slope}")

In [9]:
# USING A SIMPLE LINEAR REGRESSION MODEL

x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])
test_one = np.array([7, 8, 9, 10, 11, 12]).reshape((-1, 1))
test_two = np.array([1, 2, 3, 4, 5, 6]).reshape((-1, 1))

# you need to fit the model before you can use it, otherwise you will get an error.
model = LinearRegression().fit(x, y)

get_model_details(model) 

# and now to make your first prediction
first_prediction = model.predict(x)
second_prediction = model.predict(test_one)
third_prediction = model.predict(test_two)

print(f"\nFirst linear prediction:\n{first_prediction}")
print(f"\nSecond linear prediction:\n{second_prediction}")
print(f"\nThird linear prediction:\n{third_prediction}")
    

the coefficient r_squared is 0.7158756137479542.
the y-intercept is 5.633333333333329
the slope is [0.54]

First linear prediction:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]

Second linear prediction:
[ 9.41333333  9.95333333 10.49333333 11.03333333 11.57333333 12.11333333]

Third linear prediction:
[6.17333333 6.71333333 7.25333333 7.79333333 8.33333333 8.87333333]


In [46]:
# USING MULTIPLE LINEAR REGRESSION(NOTHING REALLY DIFFERENT...............)

x = [
        [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
    ]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

second_model = LinearRegression().fit(x, y)
get_model_details(second_model)

multi_prediction = second_model.predict(x)
print(f"\nFirst multi-linear prediction:\n{multi_prediction}")
    

the coefficient r_squared is 0.8615939258756776.
the y-intercept is 5.52257927519819
the slope is [0.44706965 0.25502548]

First multi-linear prediction:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [47]:
# .............sometime later, look at polynomial regression

In [ ]:
# -------------------------------------------------------------------------------------------------------------